# Generated by Django 5.1.3 on 2024-11-30 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LeaderboardModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now=True)),
                ("level", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="GamerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=40)),
                ("username", models.CharField(max_length=120)),
                (
                    "leaderboard",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gamer",
                        to="api.leaderboardmodel",
                    ),
                ),
            ],
        ),
    ]
